version: '3.8'
services:
  world-places:
    build: .
    image: world-places-nextjs:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.http.routers.world-places.rule=Host(`kener.paulicstudios.de`)
      - traefik.http.routers.world-places.entrypoints=web,websecure
      - traefik.http.routers.world-places.tls.certresolver=myresolver
      - traefik.http.services.world-places.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
    networks:
      - proxy

networks:
  proxy:
    external: true
